name: Deploy to GitHub Pages
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/newdark' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - run: npm ci
      - run: npm run deploy
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages-newdark
          folder: build
